-- local keymap = {
--   preset = "none",
--   ["<C-space>"] = { "show", "show_documentation", "hide_documentation" },
--   ["<C-e>"] = { "hide", "fallback" },
--
--   ["<Up>"] = { "select_prev", "fallback" },
--   ["<Down>"] = { "select_next", "fallback" },
--   ["<C-p>"] = { "select_prev", "fallback" },
--   ["<C-n>"] = { "select_next", "fallback" },
--
--   -- snippet_forward: Jumps to the next snippet placeholder
--   -- snippet_backward: Jumps to the previous snippet placeholder
--   ["<CR>"] = { "accept", "fallback" },
--   ["<Tab>"] = {
--     "select_next",
--     "snippet_forward",
--     "fallback",
--   },
--   ["<S-Tab>"] = { "select_prev", "snippet_backward", "fallback" },
--
--   ["<C-b>"] = { "scroll_documentation_up", "fallback" },
--   ["<C-f>"] = { "scroll_documentation_down", "fallback" },
-- }

-- return {
--   {
--     "saghen/blink.cmp",
--     opts = function(_, opts)
--       opts.completion.list = { selection = "auto_insert" }
--       opts.keymap = keymap
--     end,
--   },
-- }

return {}
